### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by inShu** [ButterflyStats/butterfly#4]
Hi,
Proto-data and wrappers are out of date for current situation. I'm somehow managed to handle this, but
I'm catching some kind of floating problem with every replay parsing: flattened_serializer.hpp:94: FS out-of-bounds.
Do you have any suggestions for people who is trying to use your framework at present?

Thank you

**Comment by Noxville** [comment]
Hey there. There's a few people who use this project, but for specific aspects of it. The javascript bindings for example only 1 project uses them that I'm aware of, but I can update them if you'd like them.

At datdota for example we use this for processing audio from pro matches - and this currently works fine. It's highly possible that there are some missing protos and data-types, simply because they're not used in pro matches or by people who use the project for non-pro matches.

In either case updating the protos and regenerating new wrappers isn't too difficult - I'll try fix it up this week.
